version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo "install cypress dependencies..."
      - npm ci
  build:
    commands:
      - npm install
      - node_modules/.bin/cypress run
