## buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm ci
      - npm install
  pre_build:
    commands:
      - npx cypress run
  build:
    commands:
      - npm run start:ci &
      - npx cypress run --record
